### ISSUE TITLE
dataframe_to_ccd_items(df) not working for level1b

### ISSUE THREAD

**Issue by donal-mur** [innosat-mats/MATS-L1-processing#105]
# 🐛 Description

It expects  ImageData that is not included in level1b -  Rather ImageCalibrated
Suggest that image calibrated is put in to ['Image'] as ImageData is but that it is change from a list of arrays to a 2D-array. np.stack(ImageCalibrated) and that a flag Version is added to indicate if the CCDItem is 1a or 1b.

# 🔢 To reproduce

# ✌🏽 Expected behaviour

Return ccditem

# Traceback

```
-> 3803     return self._engine.get_loc(casted_key)
   3804 except KeyError as err:

File ~/opt/anaconda3/envs/Matsanalysis/lib/python3.10/site-packages/pandas/_libs/index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File ~/opt/anaconda3/envs/Matsanalysis/lib/python3.10/site-packages/pandas/_libs/index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'ImageData'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[40], line 1
----> 1 ccd_items = dataframe_to_ccd_items(df[df.CCDSEL == 6])

File ~/projekt/SIW/MATS-L1-processing/src/mats_l1_processing/read_parquet_functions.py:172, in dataframe_to_ccd_items(ccd_data, remove_empty, remove_errors, remove_warnings)
    158 """Returns a list of CCD Items converted from the input DataFrame
...
   3808     #  InvalidIndexError. Otherwise we fall through and re-raise
   3809     #  the TypeError.
   3810     self._check_indexing_error(key)

KeyError: 'ImageData'
```

**Comment by skymandr** [comment]
Will you want to use CCD item for Level1B as well? The functions producing CCD items are written only with L1A in mind, and should not be used for L1B at the present, since those functions do a lot of manipulations that are not appropriate for L1b.

It could, and possibly should, probably be re-written to something more general.

**Comment by donal-mur** [comment]
Ok I agree. Probably just as good to use df to dict or something else . 
Will close it

**Comment by skymandr** [comment]
> Ok I agree. Probably just as good to use df to dict or something else . Will close it

I'm not sure what you are agreeing with. I was suggesting that the parquet-reading functions ought to be generalised! :)

But yes, if the CCD item scheme is not how you want to work with L1B, then "fixing" it in that way is not the way to go.

**Comment by donal-mur** [comment]
Going to reopen this-  We can call it Level1bitem to distinguish from the processing involved in l1a but the same type of structure might be needed - Will test with sending df instead

**Comment by donal-mur** [comment]
We have some functions for getting heights for pixels that take ccditem as input to get nrow, ncol  etc - 
They seem to work if I send df instead. so maybe not a problem - won't close yet .
The biggest problem is the lack of qprime

**Comment by skymandr** [comment]
This would be easy to fix, but first I want to know:

1) that you want me to work on this (question primarily for @OleMartinChristensen), and
2) what you want in the L1b-structure (_i.e._ is @donal-mur's suggestion of putting a converted `ImageCalibrated` in `Image` the way you want it)

**Comment by donal-mur** [comment]
I would say low priority -- I have a workaround  for the coordinate functions once qprime #106 is fixed -

**Comment by skymandr** [comment]
Can this be closed?

**Comment by donal-mur** [comment]
yes if it is now in the l1b which I think it is
