### ISSUE TITLE
Qprime missing in L1b record

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/MATS-L1-processing#106]
We have some functions for getting heights for pixels that take ccditem as input to get nrow, ncol  etc - 
They seem to work if I send df instead. so maybe not a problem - won't close yet .
The biggest problem is the lack of qprime

_Originally posted by @donal-mur in https://github.com/innosat-mats/MATS-L1-processing/issues/105#issuecomment-1418702861_
            

## Definition of done
- [x] `qprime` is propagated, fixed in #108
- [x] L1A -> L1B is rerun in its entirety

**Comment by skymandr** [comment]
@donal-mur What is qprime called in the CCD structure? Just `qprime` (no capital letters)?

What data-type is it? If an array, what shape?

**Comment by donal-mur** [comment]
After calibration
dict_keys(['EXP Date', 'File', 'ProcessingTime', 'RamsesTime', 'QualityIndicator', 'LossFlag', 'VCFrameCounter', 'SPSequenceCount', 'TMHeaderTime', 'TMHeaderNanoseconds', 'SID', 'RID', 'CCDSEL', 'EXP Nanoseconds', 'WDW Mode', 'WDW InputDataWindow', 'WDWOV', 'JPEGQ', 'FRAME', 'NROW', 'NRBIN', 'NRSKIP', 'NCOL', 'NCBIN FPGAColumns', 'NCBIN CCDColumns', 'NCSKIP', 'NFLUSH', 'TEXPMS', 'GAIN Mode', 'GAIN Timing', 'GAIN Truncation', 'TEMP', 'FBINOV', 'LBLNK', 'TBLNK', 'ZERO', 'TIMING1', 'TIMING2', 'VERSION', 'TIMING3', 'NBC', 'BC', 'ImageFileName', 'ImageData', 'Warnings', 'Errors', 'afsAttitudeState', 'afsGnssStateJ2000', 'afsTPLongLatGeod', 'afsTangentH_wgs84', 'afsTangentPointECI', 'HTR1A', 'HTR1B', 'HTR1OD', 'HTR2A', 'HTR2B', 'HTR2OD', 'HTR7A', 'HTR7B', 'HTR7OD', 'HTR8A', 'HTR8B', 'HTR8OD', 'IMAGE', 'channel', 'flipped', 'id', 'temperature_ADC', 'temperature', 'temperature_HTR', 'CCDunit', 'qprime', 'image_calibrated'])

so called qprime content array([-0.7066656 , -0.00353693,  0.7075217 , -0.0049312 ], dtype=float32)

**Comment by skymandr** [comment]
Thanks!
