### ISSUE TITLE
Variables missing in L1b

### ISSUE THREAD

**Issue by bjornlindr** [innosat-mats/MATS-L1-processing#110]
Retrieving L1b data the following variables are missing compared to when you run calibrations locally (see: https://github.com/innosat-mats/MATS-L1-processing/issues/106#issuecomment-1418714171)

Some of these are missing cause they have removed the spaces (or changed name?) For example, you get GAINmode instead of GAIN mode. Some variables however seem to be missing, I have indicated at least some of these. Any other that should come through?

File
EXP Nanoseconds
WDW Mode
WDW InputDataWindow
NCBIN FPGAColumns
NCBIN CCDColumns
GAIN Mode
GAIN Timing
GAIN Truncation
BC
ImageFileName
ImageData
**Warnings**
**Errors**
IMAGE
**channel**
**flipped**
**id**
**temperature_ADC**
**temperature**
**temperature_HTR**
**CCDunit**
image_calibrated

image_calibrated comes out named ImageCalibrated

**Comment by OleMartinChristensen** [comment]
Its unfortunately a bit of a chaos. But for the future all data coming out of l1a processing should not have spaces. And then I think we need to sit down and figure out what variables we want included in the l1b data.

**Comment by donal-mur** [comment]
For Andreas
We had a meeting on Friday and agreed the following
In addition to the new variables defined in 1 of 4 tasks
[Lat/Lon for track](https://github.com/innosat-mats/MATS-L1-processing/issues/110#top)
#6 
We would like the following variable to follow along from l1a

channel, flipped, Temperature, 
we noted that some had got new names  eg errors became calibrationerror. but we can live with that :-)

**Comment by skymandr** [comment]
> channel, flipped, Temperature,

Does this refer to an attribute called `Temperature` or to one or all of `temperature`, `temperature_ADC` and/or `temperature_HTR`?

**Comment by donal-mur** [comment]
I think they mean the one in ccditem['Temperature']

**Comment by donal-mur** [comment]
I think they mean the one in ccditem['Temperature']

**Comment by skymandr** [comment]
> I think they mean the one in ccditem['Temperature']

As far as I can tell there is no such item.
