### ISSUE TITLE
Processing fails due to missing table

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/MATS-L1-processing#128]
# 🐛 Description
The file 
`ops-payload-level1a-v0.5/2022/12/19/7/MATS_OPS_Level0_VC1_APID100_20221218-130207_20221219-131101.parquet`
silently fails processing. No error message is issued, and the file is put back in the queue even when re-run. It seems that what happens is that the file runs into the wall time limit of 15 minutes. Maybe this is an issue with non-existing tables that need to be computed live or something like that..?

*UPDATE:* The processing now fails early and gives an error message confirming that the table is missing from the instrument data.

From discussions on the project Discord:

>  I think this is some a special test where we were running with a non-standard binning for a long time. With no standard binning the non-linearity coefficients need to be calculated for each image (unless force_table=True). Thus it takes a long time to correct for non linearity (several seconds per image). I could generate a table for this case, but TBH Im not sure if these measurements ended up being useful at all. I think it might be the polarization measurements

# ✌🏽 Expected behaviour
Ideally that the file is processed, but at least an error would be nice...

# Definition of done
- [ ] generate table for the test
- [ ] update instrument data
- [ ] rerun processing of file

**Comment by skymandr** [comment]
@OleMartinChristensen I think this can be closed now, because you no longer rely on the tables, right?

**Comment by skymandr** [comment]
> @OleMartinChristensen I think this can be closed now, because you no longer rely on the tables, right?

This might apply to other issues, like the ones with binning etc. as well. Not sure what you've changed.

**Comment by OleMartinChristensen** [comment]
Yes

**Comment by skymandr** [comment]
> Yes

I'll close this then. Feel free to close other similar ones, that you know are no-longer applicable!
