### ISSUE TITLE
Flip Nadir image left to right

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#129]

**Comment by skymandr** [comment]
Is this done?

**Comment by lindamegner** [comment]
I think so. Louis, do you know if the NADIR image is the right way around - so that left is left with forward being forward in the orbit?
@Kernl67

**Comment by Kernl67** [comment]
The up direction in the image is the forward direction, but the right part of the image corresponds to the left side of MATS. Given the orbit, the left part of the ccd sees the area closest to the day side, but it is the right side of the images that are always brighter.
Just note that my nadir geolocation code take this into account.
