### ISSUE TITLE
Processing failes due to bad index.

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/MATS-L1-processing#159]
# 🐛 Description

Artifact correction fails for ~20 files due to `argmin` returning `-1` as index, which the `Series` doesn't appreciate. The fact that `argmin` returns `-1` probably indicates an error, but I cannot reproduce it and I'm not sure what it means.

## Questions
- [x] is `argmin` returning `-1` indicative of an error?
- [x] if so, how should that error be handled?

# 🔢 To reproduce
Process _e.g._ `ops-payload-level1a-v0.6/2023/4/7/6MATS_OPS_Level0_VC1_APID100_20230407-122205_20230408-122903.parquet`

# ✌🏽 Expected behaviour

Either an error or a correctly processed image.

# 💻 Traceback
```
ops-payload-level1a-v0.6/2023/4/7/6/MATS_OPS_Level0_VC1_APID100_20230407-122205_20230408-122903.parquet: -1 (<class 'KeyError'>; line 993, in artifact_correction; mask = artifact_masks['bias_mask'][best_ind];)
```

**Comment by Kernl67** [comment]
It happens when the L1a data has no geolocation data
then `ccditem["nadir_az"]` is` NaN`
so `azimuth` has the value `nan` in `np.argmin(np.abs(mask_azimuth - azimuth))`
`np.abs(mask_azimuth - azimuth)` is a list of `nan` values
that's why `np.argmin` outputs `-1`

**Comment by Kernl67** [comment]
I added a check in the `artifact_correction` function used in the `L1a` to `L1b` processing that raises a ValueError when `nadir_az` is `nan`

**Comment by Kernl67** [comment]
When this issue happens, there is no geolocation or attitude data in the corresponding L1a `ccditem`
in the error to be reproduced, the geolocation values of the failing `ccditem` are :
Warnings                                                                    None
Errors                                                                      None
afsAttitudeState                                            [nan, nan, nan, nan]
afsGnssStateJ2000                                 [nan, nan, nan, nan, nan, nan]
afsTPLongLatGeod                                                      [nan, nan]
afsTangentH_wgs84                                                          [nan]
afsTangentPointECI                                               [nan, nan, nan]
satlat                                                                       NaN
satlon                                                                       NaN
satheight                                                                    NaN
TPlat                                                                        NaN
TPlon                                                                        NaN
TPheight                                                                     NaN
nadir_sza                                                                    NaN
TPsza                                                                        NaN
TPssa                                                                        NaN
nadir_az                                                                     NaN
TPlocaltime                                                                     

This indicates that the error occurs likely upstreams in the processing pipeline

**Comment by Kernl67** [comment]
artifact_correction_index

**Comment by skymandr** [comment]
Thanks @Kernl67 . I'm looking into it in L1A. I think what happens is that we fail to drop rows where interpolation from platform fails.
