### ISSUE TITLE
move all experimental functions to seperate python file

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#17]

**Comment by lindamegner** [comment]
move LindasCalibrationfiles to codcalibrationreport

**Comment by lindamegner** [comment]
Removed LindasCalibrationFunctions and distributed used functions into experimental_utils.py and items_units_functions.py

read_in_functions.py:
readprotocol moved to experimental_utils.py
searchlist removed (was unused)
ismember removed (was unused)
find_CCDitem_matching_protocol_entry renamed to find_CCDitem_matching_PicID


LindasCalibrationFunctions.py
moved filter_on_time  to experimental_utils.py
removed  printvar selectimage (was unused)
removed  selectimage (was unused)
moved UniqueValuesInKey to  test_desmearing_algorithm
