### ISSUE TITLE
Update Nadir desmearing algoritm to assume constant (not linearly increasing) field

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#178]
# 📋 Info

The naidr desmearing algoritm currently assumes that the field is linearly increasing where the image is cropped (as it is for the other channels) but the nadir field does not have any increasing rayleigh and should be assumed constant (or even decreasing due to the baffle interference.

Ipsum lorem...

# 🏁 DoD

- [ ] A
- [ ] B
- [ ] C

**Comment by donal-mur** [comment]
If the image is flat then the extrapolation will be flat.
I check the nadir there are 14 binned rows with 36 ccd rows  per super pixel - that gives 504 so there will be some filling  out but quite little. If the image is very structured near the edge then that could give an effect but only in the affected columns -- If we were to take a constant value - what value should that be?
