### ISSUE TITLE
bug in bias subtraction affecting top right corner pixel

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#232]
# 🐛 Description
we seem to have a but in the bias subtraction affecting top right corner pixel. seen in ir1 and ir2 . probably is there for all channels

What should have happened

# 📷 Screenshots
![image](https://github.com/user-attachments/assets/9bfdb343-eebd-4ac5-955c-4e1b37c623c7)
If applicable

# 💻 Traceback

```
Paste logs here...
```

**Comment by lindamegner** [comment]
the issue was not in hte bias correction but in the single event maps. closing this issue and opening another one with more appropriate title

**Comment by skymandr** [comment]
Superseded by #233
