### ISSUE TITLE
fix and uncomment lineatity test in pytests

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#26]
Linda commented out the linearity test in pytests since I was missing stuff so that it did not run.  It needs to be fixed and uncommented. Here is the error message I got:

(MatsLevel1) lindamegner@MacBook-Pro-6 MATS-L1-processing % pytest
================================================ test session starts ================================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/lindamegner/MATS/retrieval/git/MATS-L1-processing, configfile: setup.cfg, testpaths: tests
plugins: anyio-3.3.2
collected 5 items / 1 error / 4 selected                                                                            

====================================================== ERRORS =======================================================
________________________________ ERROR collecting tests/test_database_generation.py _________________________________
ImportError while importing test module '/Users/lindamegner/MATS/retrieval/git/MATS-L1-processing/tests/test_database_generation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../miniconda3/envs/MatsLevel1/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_database_generation.py:5: in <module>
    from database_generation.linearity import get_non_lin_important
E   ImportError: cannot import name 'get_non_lin_important' from 'database_generation.linearity' (/Users/lindamegner/MATS/retrieval/git/MATS-L1-processing/src/database_generation/linearity.py)
============================================== short test summary info ==============================================
ERROR tests/test_database_generation.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================= 1 error in 1.47s ==================================================
(MatsLevel1) lindamegner@MacBook-Pro-6 MATS-L1-processing %

**Comment by lindamegner** [comment]
It did not work just to comment out the linearity. Seems like there are several issues with pytest.... I (linda) added linearity back in and let you (OM) fix this when you are back.

**Comment by OleMartinChristensen** [comment]
fixed
