### ISSUE TITLE
Depricated fields?

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#29]
"NColBinCCD": 80,
    "NColBinFPGA": 0.0,
    "DigGain": 0,
    "SigMode": 0,

I think these fields are depricated and should be replaced?

**Comment by lindamegner** [comment]
Deprecated? Do you mean duplicated? If so, yes they may well be, many of them are, its an inheretance from the imgview and old versions of rac-reader. And yes, it should be removed. But it is not a bug, so maybe I misunderstand you...

**Comment by lindamegner** [comment]
duplacated issue. will be done in issue #7.
