### ISSUE TITLE
dark picture / flatfield cutout is wrong? 

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#48]
dark_fullpic = calculate_dark(CCDitem)
    
image_dark_sub = (
        image
        - dark_fullpic[
            CCDitem["NRSKIP"] : CCDitem["NRSKIP"] + CCDitem["NROW"],
            CCDitem["NCSKIP"] : CCDitem["NCSKIP"] + CCDitem["NCOL"] + 1,
        ]
    )

I think caluculate_dark allready takes into account nrskip and ncskip...

**Comment by OleMartinChristensen** [comment]
Same issue in flatfield_calibration

**Comment by lindamegner** [comment]
Yes, it looks like you are right. But I dont have any image with NSKIP to test on.  So you can remove it  and test? Or send me images to test with?

**Comment by lindamegner** [comment]
fixed
