### ISSUE TITLE
Put back get_linearized_image. Too long time to process

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#52]
I had to comment out get_linearized_image in L1_calibrate becasue it took too long to process for the binned data you sent me. 

image_linear,error_flags_linearity = get_linearized_image(CCDitem, image_bias_sub)

**Comment by OleMartinChristensen** [comment]
fixed, a new table is now generated if there is no table. So first time running a image it can take some time but after that it is fast.
