### ISSUE TITLE
why calibration_data.toml is symbolic link

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#56]
why is the calibration_data.toml in scripts made into a symbolic link to a calibration_data_linda?

**Comment by lindamegner** [comment]
I think that May have been som ols hack i din. I din not relise then that
it would appar that way on git. Remove it.

Den fre 7 okt. 2022 21:00OleMartinChristensen ***@***.***>
skrev:

**Comment by OleMartinChristensen** [comment]
ok symlink removed
