### ISSUE TITLE
remove reanaming in add_and_rename

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#7]

**Comment by lindamegner** [comment]
I assume that what we had in mind here was this:
    # TODO LM June 2020: Change  all code so that the new names, i. CCDitem['NCBIN CCDColumns'] and CCDitem['NCBIN FPGAColumns'] are used instead of the old.
 
For this I need a list of what level 0 actually outputs.  I used to be able to open CCD.csv to see this. Anyway, I think we need to look at this together. I assign you and then we'll discuss it and I can do the changes.

**Comment by lindamegner** [comment]
Detta är vad de ska heta
File	ProcessingDate	RamsesTime	QualityIndicator	LossFlag	VCFrameCounter	SPSequenceCount	TMHeaderTime	TMHeaderNanoseconds	SID	RID	CCDSEL	EXP Nanoseconds	EXP Date	WDW Mode	WDW InputDataWindow	WDWOV	JPEGQ	FRAME	NROW	NRBIN	NRSKIP	NCOL	NCBIN FPGAColumns	NCBIN CCDColumns	NCSKIP	NFLUSH	TEXPMS	GAIN Mode	GAIN Timing	GAIN Truncation	TEMP	FBINOV	LBLNK	TBLNK	ZERO	TIMING1	TIMING2	VERSION	TIMING3	NBC	BC	Image File Name	Error
