### ISSUE TITLE
warning with large dataframes

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#78]
# ❓ Questions
I just seem to be getting this warning, which is a bit annoying. Is this typical for data frames with many rows?

_pydevd warning: Computing repr of df (DataFrame) was slow (took 0.27s)_

**Comment by e-larsson** [comment]
Have never encountered this warning, maybe this thread can help https://stackoverflow.com/questions/71695716/pydevd-warnings-in-visual-studio-code-debug-console
