### ISSUE TITLE
check if NCSKIP/NRSKIP are correctly handled in the calibration

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#88]
# 📋 Info

check if NCSKIP/NRSKIP are correctly handled in the calibration

# 🏁 DoD

- [ ] A
- [ ] B
- [ ] C

**Comment by OleMartinChristensen** [comment]
we feel confident this is correct now, right @lindamegner ?

**Comment by lindamegner** [comment]
jo det tycker jag.
