### ISSUE TITLE
Agree on how to version control and update instrument data

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/MATS-L1-processing#98]
# 📋 Info

We need a routine for how to update and version control instrument data for use in the L1B Lambda

Version (a tag in the toml file?) should be propagated to the resulting parquet file.

# 🏁 DoD

- [x] Agree on routine
- [x] Implement versioning
- [x] Propagate version to parquet

**Comment by joakimmoller** [comment]
subrepo?
